/** Stage the binding shim that pins `@gpuiv/native` to one `.node` file.
 *
 * The generated napi loader picks the binary at runtime through ~20
 * try/catch `require` branches (universal → arch → optional package). Bundled
 * as-is, that either embeds several binaries or none — it is exactly the
 * "indirect require" Bun warns will not bundle correctly. We stage a shim
 * with one literal `require` of the chosen file, so the bundler embeds
 * exactly one binding per product.
 *
 * Directly resolving `@gpuiv/native` to the `.node` file does not work:
 * the bundler cannot see named exports inside a binary module ("No matching
 * export … for import"). The shim re-exports each name explicitly, which
 * cjs-module-lexer can read. */

import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { resolveFromApp } from "./targets.js"

const FALLBACK_EXPORTS = [
  "GpuixCanvas2DCore",
  "GpuixRenderer",
  "TestGpuixRenderer",
  "hasTestGpuixRenderer",
]

/** The napi loader's tail re-exports every napi class one by one
 * (`module.exports.X = nativeBinding.X`); mirror that list in the shim. */
export function bindingExportNames(configDir: string): string[] {
  const loader = resolveFromApp(configDir, "@gpuiv/native", "index.js")
  if (loader) {
    const names = [...readFileSync(loader, "utf8").matchAll(/module\.exports\.(\w+)\s*=/g)].map((m) => m[1])
    if (names.length > 0) return names
  }
  return FALLBACK_EXPORTS
}

export function stageBindingShim(opts: {
  stagingDir: string
  nodeFile: string
  targetName: string
  configDir: string
}): string {
  mkdirSync(opts.stagingDir, { recursive: true })
  const nodeCopy = path.join(opts.stagingDir, path.basename(opts.nodeFile))
  copyFileSync(opts.nodeFile, nodeCopy)

  const names = bindingExportNames(opts.configDir)
  const shim = path.join(opts.stagingDir, "native-binding.js")
  writeFileSync(
    shim,
    [
      `// Generated by @gpuiv/packager for target ${opts.targetName}.`,
      `// Pins @gpuiv/native to the one binary embedded in this product.`,
      `const binding = require('./${path.basename(nodeCopy)}')`,
      `module.exports = binding`,
      ...names.map((name) => `module.exports.${name} = binding.${name}`),
      "",
    ].join("\n"),
  )
  return shim
}
